# Generated by Django 5.0.1 on 2024-01-18 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_baseuser_email_is_confirmed_alter_otp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 10, 27, 25, 687102)),
        ),
    ]
