# Generated by Django 5.0.1 on 2024-01-20 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_baseuser_role_alter_otp_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 13, 36, 2, 429741)),
        ),
    ]
